### ISSUE TITLE
pyminifier --destdir not working

### ISSUE THREAD

**Issue by divyanayan** [liftoff/pyminifier#112]
I was using pyminifier --destdir to send minfied files to a specific directory but it gives an error that specified file is not found .  i used with the path  given in the documentation as well still gives the same error .

>pyminifier  a.py --destdir=./minified

Error : FileNotFoundError: [WinError 3] The system cannot find the path specified: '--destdir=./minified'

**Comment by varunsapre** [comment]
The format of the command should be `pyminifier --destdir=./minified a.py `

**Comment by divyanayan** [comment]
> pyminifier --destdir=./minified a.py
Thanks varun for the reply ,but in this case i made a directory as say hello and hence command would be pyminifier --destdir=./hello a.py
.i was expecting a file to be created in hello directory

**Comment by varunsapre** [comment]
According to the documentation, the `--destdir` option can be used only when handling multiple files. If you want to run it only for one file, you could try using `pyminifier -o hello/a.py a.py`

**Comment by divyanayan** [comment]
yes i was able to that for one file ,i  used --outfile option . is this the command for multiple files pyminifier --destdir=./hello and i am in the folder where multiple files are .Assuming this way i can reduce size of python libs as well ?

**Comment by divyanayan** [comment]
>pyminifier --destdir=./hello a.py inserts.py  i was able to achieve what is expected ..thanks a lot  Varun for guiding me.Would like to know this i can use to reduce python lib size as well right ,mainly to overcome AWS lambda size limtation of 50 mb.
