### ISSUE TITLE
Wrong parameter name in obfuscate.obfuscation_machine invocation

### ISSUE THREAD

**Issue by rsc1975** [liftoff/pyminifier#32]
In the file pyminifier/compression.py,  the call to obfuscate.obfuscation_machine uses a wrong parameter name

The lines:

    221 name_generator = obfuscate.obfuscation_machine(
    222	                    use_unicode=True, count=identifier_length
    …	
    229	            name_generator = obfuscate.obfuscation_machine(
    230	                count=identifier_length)

Should be:

    221 name_generator = obfuscate.obfuscation_machine(
    222	                    use_unicode=True, identifier_length=identifier_length
    …	
    229	            name_generator = obfuscate.obfuscation_machine(
    230	                identifier_length=identifier_length)

This issue is generating an error with `--pyz` option.

**Comment by liftoff** [comment]
Thanks for including the fix! I'll get an update pushed shortly (doesn't get much easier!).

**Comment by liftoff** [comment]
Closing this one out since I'm pretty sure your fix was all that it needed.
