### ISSUE TITLE
Multiple files not working

### ISSUE THREAD

**Issue by sdekrijger** [liftoff/pyminifier#33]
Hi,
There seems to be an issue with
$ pyminifier --dest-dir=/dev/shm ./*.py

The only output is:
 # Created by pyminifier (https://github.com/liftoff/pyminifier)

On commit 2ed2eaf it's working fine, after that it's the above. 

Br, 
Sjef.

**Comment by liftoff** [comment]
This should be all fixed now.  Can you grab the latest code and confirm?  Thanks.
