### ISSUE TITLE
Add option for obfuscation imports

### ISSUE THREAD

**Issue by rominf** [liftoff/pyminifier#4]
I propose you to add possibility to obfuscate imports. So, instead of having:

``` python
from numpy import array
import re
...
array(...)
re.match(...)
```

we can have:

``` python
from numpy import array as σΣΕξ
import re as αβ
...
σΣΕξ(...)
αβ.match(...)
```

I think it's not hard to do, it will increase unreadability.

`match` is still readable. I think that monkey patching can help, but it can break some code:

``` python
import re as αβ
αβ.γx = αβ.match
```

**Comment by TheTechRobo** [comment]
I was just trying this, and it seems like this feature was already added...
