### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by panofish** [liftoff/pyminifier#7]
My code is good, runs fine normally and even runs fine after compiling to exe with pyinstaller.  However, when I try to use pyminifier, I get IndentationError.  There are no indentation errors and I have tried both "all spaces" and "all tabs" for my indentations with no luck.  Not sure what the problem is, but I think the indentation error is a "red herring".  Must be something to do with more complex python, because it seems to work with very simple python programs.  Sorry I can't provide my source code. :(

Traceback (most recent call last):
  File "C:\Users\alilly\Downloads\pyminifier-master\pyminifier-master\pyminifier\pyminifier.py", line 438, in <module>
    main()
  File "C:\Users\alilly\Downloads\pyminifier-master\pyminifier-master\pyminifier\pyminifier.py", line 402, in main
    source = minification.minify(tokens, options)
  File "C:\Users\alilly\Downloads\pyminifier-master\pyminifier-master\pyminifier\minification.py", line 516, in minify
    result = reduce_operators(result)
  File "C:\Users\alilly\Downloads\pyminifier-master\pyminifier-master\pyminifier\minification.py", line 191, in reduce_operators
    for tok in tokenize.generate_tokens(io_obj.readline):
  File "C:\Python27\lib\tokenize.py", line 351, in generate_tokens
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 962
    self.book = book
    ^
IndentationError: unindent does not match any outer indentation level

**Comment by liftoff** [comment]
Closing this issue since I haven't heard back from the original submitted.  I'm going to assume it's fixed since it appears to be from my end.

**Comment by panofish** [comment]
I'm not using it now and I don't need it now.
So I don't know if the problem was fixed or not.

Alan

**Comment by dajay0** [comment]
I think this issue is still not resolved (if  you are still looking to fix it). Here is an example:

My command line (needless to say I am on Windows) -----
```
pyminifier.exe -o t.py -O --nominify temp.py
```

File temp.py is  ------
```
class LoginPage:
        gladeFile = 'LoginPage.glade'
        t = 10
```
Output generated is --------
```
class x:
        d = 'LoginPage.glade'
 t = 10
# Created by pyminifier (https://github.com/liftoff/pyminifier)
```
----------
Notice the difference in the indentation in second and third lines in the output.

Also if I drop the --nominify flag here the process does not even complete. It throws indentation error even before the conversion happens. Hopefully this will help you to narrow down on the problem.
